x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/proxmox.svg
  urls:
    - https://pve.proxmox.com/pve-docs/
services:
  proxmox:
    hostname: pve
    image: dockurr/proxmox
    container_name: proxmox
    privileged: true
    environment:
      PASSWORD: ${ROOTPWD}
    ports:
      - 8006:8006
    volumes:
      - proxmoxve:/var/lib/vz
      - config:/var/lib/pve-cluster
    stop_grace_period: 2m
    restart: unless-stopped
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/proxmox.svg
volumes:
  proxmoxve:
    name: proxmox-volume
  config:
    name: proxmox-config
