x-arcane:
  icon: https://upload.wikimedia.org/wikipedia/commons/d/db/Samba_logo_2010.svg
  urls:
    - https://www.samba.org
services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      NAME: ${SMBNAME}
      USER: ${SMBUSER}
      PASS: ${SMBPASS}
    # Optional, default true
      RW: true
    # Optional, default 1000
      UID: ${UID}
    # Optional, default 1000
      GID: ${GID}
    ports:
      - 445:445
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - samba:/storage
    restart: unless-stopped
    labels:
      com.getarcaneapp.arcane.icon: https://upload.wikimedia.org/wikipedia/commons/d/db/Samba_logo_2010.svg
volumes:
  samba:
    name: smb-volume
