x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/myspeed.png
  urls:
    - https://myspeed.dev/
services:
  MySpeed:
    image: germannewsmaker/myspeed
    container_name: MySpeed
#    user: ${UID}:${GUID}
    restart: unless-stopped
    ports:
      - 8080:5216
    volumes:
      - myspeed:/myspeed/data
    networks:
        - myspeed
    healthcheck:
      test: |
        sh -c 'ps aux | grep -q "[n]ode server" && 
               wget --spider -q -O- http://localhost:5216 > /dev/null && 
               echo "Myspeed is healthy" || exit 1'
      start_period: 15s
      start_interval: 5s
      interval: 30s
      timeout: 10s
      retries: 3  
    labels:
      - com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/myspeed.png
      - "autoheal=true"
# The auto-healer watches other containers and restarts unhealthy ones
  autoheal:
    image: willfarrell/autoheal:latest
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: "autoheal"
      AUTOHEAL_INTERVAL: 30
      AUTOHEAL_START_PERIOD: 60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/fitbit-health-dashboard.png
networks:
  myspeed:
   name: myspeed_bridge
   driver: bridge
volumes:
  myspeed:
    name: Myspeed_Volume