x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/owntone.svg
  urls:
    - https://owntone.github.io/owntone-server/
services:
  owntone:
    image: docker.io/owntone/owntone:latest
    container_name: OwnTone
    network_mode: host
    environment:
      - UID=${UID}
      - GID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - owntone:/etc/owntone
      - media:/srv/media:ro
    tmpfs:
      - /var/cache/owntone:rw,size=512m,mode=1777,noexec,nodev,nosuid
    restart: unless-stopped
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/owntone.svg
volumes:
  owntone:
    name: owntone
  media:
    name: Musique
    driver: local
    driver_opts:
      type: cifs
      device: "//${SMBSRV}/${SMBSHARE}"
      o: "username=${MNTUSER},password=${MNTPWD},ro,vers=3.1.1,file_mode=0755,dir_mode=0755,iocharset=utf8"